/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SpielFeld;

/**
 *
 * @author Physik
 */
public class Spielfeld extends javax.swing.JFrame {

    /**
     * Creates new form Spielfeld
     */
    public Spielfeld() {
        initComponents();
        initFeld();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jButton1)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void initFeld() {
        // <editor-fold defaultstate="collapsed" desc="Knopf INIT">           
        jButtonA1 = new javax.swing.JButton();
        jButtonA2 = new javax.swing.JButton();
        jButtonA3 = new javax.swing.JButton();
        jButtonA4 = new javax.swing.JButton();
        jButtonA5 = new javax.swing.JButton();
        jButtonA6 = new javax.swing.JButton();
        jButtonA7 = new javax.swing.JButton();
        jButtonA8 = new javax.swing.JButton();
        jButtonB1 = new javax.swing.JButton();
        jButtonB2 = new javax.swing.JButton();
        jButtonB3 = new javax.swing.JButton();
        jButtonB4 = new javax.swing.JButton();
        jButtonB5 = new javax.swing.JButton();
        jButtonB6 = new javax.swing.JButton();
        jButtonB7 = new javax.swing.JButton();
        jButtonB8 = new javax.swing.JButton();
        jButtonC1 = new javax.swing.JButton();
        jButtonC2 = new javax.swing.JButton();
        jButtonC3 = new javax.swing.JButton();
        jButtonC4 = new javax.swing.JButton();
        jButtonC5 = new javax.swing.JButton();
        jButtonC6 = new javax.swing.JButton();
        jButtonC7 = new javax.swing.JButton();
        jButtonC8 = new javax.swing.JButton();
        jButtonD1 = new javax.swing.JButton();
        jButtonD2 = new javax.swing.JButton();
        jButtonD3 = new javax.swing.JButton();
        jButtonD4 = new javax.swing.JButton();
        jButtonD5 = new javax.swing.JButton();
        jButtonD6 = new javax.swing.JButton();
        jButtonD7 = new javax.swing.JButton();
        jButtonD8 = new javax.swing.JButton();
        jButtonE1 = new javax.swing.JButton();
        jButtonE2 = new javax.swing.JButton();
        jButtonE3 = new javax.swing.JButton();
        jButtonE4 = new javax.swing.JButton();
        jButtonE5 = new javax.swing.JButton();
        jButtonE6 = new javax.swing.JButton();
        jButtonE7 = new javax.swing.JButton();
        jButtonE8 = new javax.swing.JButton();
        jButtonF1 = new javax.swing.JButton();
        jButtonF2 = new javax.swing.JButton();
        jButtonF3 = new javax.swing.JButton();
        jButtonF4 = new javax.swing.JButton();
        jButtonF5 = new javax.swing.JButton();
        jButtonF6 = new javax.swing.JButton();
        jButtonF7 = new javax.swing.JButton();
        jButtonF8 = new javax.swing.JButton();
        jButtonG1 = new javax.swing.JButton();
        jButtonG2 = new javax.swing.JButton();
        jButtonG3 = new javax.swing.JButton();
        jButtonG4 = new javax.swing.JButton();
        jButtonG5 = new javax.swing.JButton();
        jButtonG6 = new javax.swing.JButton();
        jButtonG7 = new javax.swing.JButton();
        jButtonG8 = new javax.swing.JButton();
        jButtonH1 = new javax.swing.JButton();
        jButtonH2 = new javax.swing.JButton();
        jButtonH3 = new javax.swing.JButton();
        jButtonH4 = new javax.swing.JButton();
        jButtonH5 = new javax.swing.JButton();
        jButtonH6 = new javax.swing.JButton();
        jButtonH7 = new javax.swing.JButton();
        jButtonH8 = new javax.swing.JButton();
// </editor-fold>              
        // <editor-fold defaultstate="collapsed" desc="Knopf EventListener">
        jButtonA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonA1ActionPerformed(evt);
            }
        });
        jButtonA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonA2ActionPerformed(evt);
            }
        });
        jButtonA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonA3ActionPerformed(evt);
            }
        });
        jButtonA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonA4ActionPerformed(evt);
            }
        });
        jButtonA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonA5ActionPerformed(evt);
            }
        });
        jButtonA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonA6ActionPerformed(evt);
            }
        });
        jButtonA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonA7ActionPerformed(evt);
            }
        });
        jButtonA8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonA8ActionPerformed(evt);
            }
        });
        jButtonB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonB1ActionPerformed(evt);
            }
        });
        jButtonB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonB2ActionPerformed(evt);
            }
        });
        jButtonB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonB3ActionPerformed(evt);
            }
        });
        jButtonB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonB4ActionPerformed(evt);
            }
        });
        jButtonB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonB5ActionPerformed(evt);
            }
        });
        jButtonB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonB6ActionPerformed(evt);
            }
        });
        jButtonB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonB7ActionPerformed(evt);
            }
        });
        jButtonB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonB8ActionPerformed(evt);
            }
        });
        jButtonC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonC1ActionPerformed(evt);
            }
        });
        jButtonC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonC2ActionPerformed(evt);
            }
        });
        jButtonC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonC3ActionPerformed(evt);
            }
        });
        jButtonC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonC4ActionPerformed(evt);
            }
        });
        jButtonC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonC5ActionPerformed(evt);
            }
        });
        jButtonC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonC6ActionPerformed(evt);
            }
        });
        jButtonC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonC7ActionPerformed(evt);
            }
        });
        jButtonC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonC8ActionPerformed(evt);
            }
        });
        jButtonD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD1ActionPerformed(evt);
            }
        });
        jButtonD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD2ActionPerformed(evt);
            }
        });
        jButtonD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD3ActionPerformed(evt);
            }
        });
        jButtonD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD4ActionPerformed(evt);
            }
        });
        jButtonD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD5ActionPerformed(evt);
            }
        });
        jButtonD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD6ActionPerformed(evt);
            }
        });
        jButtonD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD7ActionPerformed(evt);
            }
        });
        jButtonD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonD8ActionPerformed(evt);
            }
        });
        jButtonE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonE1ActionPerformed(evt);
            }
        });
        jButtonE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonE2ActionPerformed(evt);
            }
        });
        jButtonE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonE3ActionPerformed(evt);
            }
        });
        jButtonE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonE4ActionPerformed(evt);
            }
        });
        jButtonE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonE5ActionPerformed(evt);
            }
        });
        jButtonE6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonE6ActionPerformed(evt);
            }
        });
        jButtonE7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonE7ActionPerformed(evt);
            }
        });
        jButtonE8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonE8ActionPerformed(evt);
            }
        });
        jButtonF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonF1ActionPerformed(evt);
            }
        });
        jButtonF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonF2ActionPerformed(evt);
            }
        });
        jButtonF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonF3ActionPerformed(evt);
            }
        });
        jButtonF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonF4ActionPerformed(evt);
            }
        });
        jButtonF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonF5ActionPerformed(evt);
            }
        });
        jButtonF6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonF6ActionPerformed(evt);
            }
        });
        jButtonF7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonF7ActionPerformed(evt);
            }
        });
        jButtonF8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonF8ActionPerformed(evt);
            }
        });
        jButtonG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonG1ActionPerformed(evt);
            }
        });
        jButtonG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonG2ActionPerformed(evt);
            }
        });
        jButtonG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonG3ActionPerformed(evt);
            }
        });
        jButtonG4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonG4ActionPerformed(evt);
            }
        });
        jButtonG5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonG5ActionPerformed(evt);
            }
        });
        jButtonG6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonG6ActionPerformed(evt);
            }
        });
        jButtonG7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonG7ActionPerformed(evt);
            }
        });
        jButtonG8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonG8ActionPerformed(evt);
            }
        });
        jButtonH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonH1ActionPerformed(evt);
            }
        });
        jButtonH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonH2ActionPerformed(evt);
            }
        });
        jButtonH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonH3ActionPerformed(evt);
            }
        });
        jButtonH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonH4ActionPerformed(evt);
            }
        });
        jButtonH5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonH5ActionPerformed(evt);
            }
        });
        jButtonH6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonH6ActionPerformed(evt);
            }
        });
        jButtonH7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonH7ActionPerformed(evt);
            }
        });
        jButtonH8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonH8ActionPerformed(evt);
            }
        });
        // </editor-fold>

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        //jButtonA8.setText("jButton1");
//        
//         //<editor-fold defaultstate="collapsed" desc=" Group Layout">
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                .addGroup(layout.createSequentialGroup()
//                        .addComponent(jButtonA1)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonB1)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonC1)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonD1)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonE1)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonF1)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonG1)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonH1)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                ).addGroup(layout.createSequentialGroup()
//                        .addComponent(jButtonA2)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonB2)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonC2)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonD2)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonE2)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonF2)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonG2)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonH2)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                ).addGroup(layout.createSequentialGroup()
//                        .addComponent(jButtonA3)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonB3)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonC3)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonD3)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonE3)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonF3)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonG3)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonH3)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                ).addGroup(layout.createSequentialGroup()
//                        .addComponent(jButtonA4)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonB4)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonC4)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonD4)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonE4)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonF4)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonG4)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonH4)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                ).addGroup(layout.createSequentialGroup()
//                        .addComponent(jButtonA5)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonB5)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonC5)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonD5)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonE5)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonF5)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonG5)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonH5)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                ).addGroup(layout.createSequentialGroup()
//                        .addComponent(jButtonA6)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonB6)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonC6)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonD6)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonE6)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonF6)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonG6)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonH6)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                ).addGroup(layout.createSequentialGroup()
//                        .addComponent(jButtonA7)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonB7)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonC7)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonD7)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonE7)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonF7)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonG7)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonH7)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                ).addGroup(layout.createSequentialGroup()
//                        .addComponent(jButtonA8)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonB8)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonC8)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonD8)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonE8)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonF8)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonG8)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jButtonH8)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                )//.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                .addGroup(layout.createSequentialGroup()
//                        .addContainerGap()
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                .addComponent(jButtonA8)
//                                .addComponent(jButtonB8)
//                                .addComponent(jButtonC8)
//                                .addComponent(jButtonD8)
//                                .addComponent(jButtonE8)
//                                .addComponent(jButtonF8)
//                                .addComponent(jButtonG8)
//                                .addComponent(jButtonH8))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                .addComponent(jButtonA7)
//                                .addComponent(jButtonB7)
//                                .addComponent(jButtonC7))
//                        .addContainerGap(237, Short.MAX_VALUE))
//        );
//
//        pack();
//    // </editor-fold>    
    }
//<editor-fold defaultstate="collapsed" desc=" Knopf Events">

    private void jButtonA1ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonA2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonA3ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonA4ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonA5ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonA6ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonA7ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonA8ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonB1ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonB2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonB3ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonB4ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonB5ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonB6ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonB7ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonB8ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonC1ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonC2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonC3ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonC4ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonC5ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonC6ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonC7ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonC8ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonD1ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonD2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonD3ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonD4ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonD5ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonD6ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonD7ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonD8ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonE1ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonE2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonE3ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonE4ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonE5ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonE6ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonE7ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonE8ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonF1ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonF2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonF3ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonF4ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonF5ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonF6ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonF7ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonF8ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonG1ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonG2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonG3ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonG4ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonG5ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonG6ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonG7ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonG8ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonH1ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonH2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonH3ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonH4ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonH5ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonH6ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonH7ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonH8ActionPerformed(java.awt.event.ActionEvent evt) {

    }
// </editor-fold> 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Spielfeld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Spielfeld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Spielfeld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Spielfeld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Spielfeld().setVisible(true);
            }
        });
    }
    private javax.swing.JButton jButtonA1, jButtonA2, jButtonA3, jButtonA4, jButtonA5, jButtonA6, jButtonA7, jButtonA8, jButtonB1, jButtonB2, jButtonB3, jButtonB4, jButtonB5, jButtonB6, jButtonB7, jButtonB8, jButtonC1, jButtonC2, jButtonC3, jButtonC4, jButtonC5, jButtonC6, jButtonC7, jButtonC8, jButtonD1, jButtonD2, jButtonD3, jButtonD4, jButtonD5, jButtonD6, jButtonD7, jButtonD8, jButtonE1, jButtonE2, jButtonE3, jButtonE4, jButtonE5, jButtonE6, jButtonE7, jButtonE8, jButtonF1, jButtonF2, jButtonF3, jButtonF4, jButtonF5, jButtonF6, jButtonF7, jButtonF8, jButtonG1, jButtonG2, jButtonG3, jButtonG4, jButtonG5, jButtonG6, jButtonG7, jButtonG8, jButtonH1, jButtonH2, jButtonH3, jButtonH4, jButtonH5, jButtonH6, jButtonH7, jButtonH8;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
